plugins {
	id 'java'
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation platform('org.junit:junit-bom:5.14.0')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation 'org.assertj:assertj-core:3.27.6'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jar {
	manifest {
		attributes 'Main-Class': 'ch.bbw.m450.tictactoe.TicTacToeMain'
	}
}

test {
	useJUnitPlatform()
	testLogging {
		events 'passed', 'skipped', 'failed'
	}
}
